### ISSUE TITLE
[native] Crypto.sha256 implementation

### ISSUE THREAD

**Issue by VzxPLnHqr** [fiatjaf/scoin#2]
So, in an effort to start testing scoin out a little more, I tried to put together a trivial scala-native app which just hashes its arguments.

However, a call to `Crypto.sha256(_)` (https://github.com/fiatjaf/scoin/blob/master/native/src/main/scala/Crypto.scala#L211), ended up throwing an exception:
```
scala.NotImplementedError: must update sn-secp256k1
```
I tried to figure out where/how to add sha256 into that library, but then got lost. It obviously must exist somewhere in there already since that library does secp256k1 signing for bitcoin and hence uses sha256. Perhaps it is just not exposed to scala-native?

**Comment by VzxPLnHqr** [comment]
I am still confused by this. Looks like `build.sbt` includes a dependency of https://github.com/nbd-wtf/sn-sha256 so sha256 should already be available for use? Why is the exception above thrown then?

**Comment by fiatjaf** [comment]
Sorry for the late response. Are you sure you're getting that error on that function specifically? I would bet it is on a different one, because sha256 is implemented, but there are some others that are not and they throw that exception.

**Comment by VzxPLnHqr** [comment]
No problem on the delay. Just slowly finding my way around. Here is the simple scala-native app that throws the exception.

```
import scoin._
import scodec.bits._ 

object Main extends App {
    Console.println("hello from native. What should we hash?")
    val m = Console.in.readLine()
    val h = Crypto.sha256(ByteVector(m.getBytes)) // this throws sn-secp256k1 not implemented exception
    Console.println(s"sha256($m) == ${h.toHex}")
}
```

I can get it to work by replacing it with the following:
`val h = ByteVector(sha256.Sha256.sha256(m).map(_.toByte))`

**Comment by fiatjaf** [comment]
Here I get this stacktrace:

```scala
scala.NotImplementedError: must update sn-secp256k1                                                                                                                                
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)                                                                                                                 
        at java.lang.Throwable.fillInStackTrace(Unknown Source)                                                                                                                    
        at scoin.Crypto$.N(Unknown Source)                                                                                                                                         
        at scoin.Crypto$.<init>(Unknown Source)                                                                                                                                    
        at <none>._SM13scoin.Crypto$G4load(Unknown Source)                                                                                                                         
        at Main$.<init>(Unknown Source)                                                                                                                                            
        at <none>._SM5Main$G4load(Unknown Source)                                                                                                                                  
        at Main.main(Unknown Source)                                                                                                                                               
        at <none>.main(Unknown Source)                                                                                                                                             
        at <none>.(Unknown Source)                                                                                                                                                 
        at <none>.__libc_start_main(Unknown Source)                                                                                                                                
        at <none>._start(Unknown Source)
```

This means the error is in the `N` value from `Crypto` which is running when `Crypto` is loaded. I don't understand why is that happening. Can you check if `N` is a `val` or a `def` on your local code?

**Comment by VzxPLnHqr** [comment]
Yes, very strange indeed. Just checked, it is 
```
def N: BigInteger =
    throw new NotImplementedError("must update sn-secp256k1")
```

**Comment by fiatjaf** [comment]
Maybe try just replacing that with `def N = BigInteger(1)` and see what happens?

**Comment by VzxPLnHqr** [comment]
> Maybe try just replacing that with `def N = BigInteger(1)` and see what happens?

Tried this and actually could not get it to compile. So it seems there might be two things going on?
1. ~~BigInteger maybe is not supported in scala native?~~ 
2. Why is `Crypto.N` even being called? My guess is that somewhere else in the library there is a `val N = Crypto.N` that is causing it to be called.

edit: Yes, turns out https://github.com/fiatjaf/scoin/blob/master/native/src/main/scala/Crypto.scala#L10 is calling `N`

**Comment by VzxPLnHqr** [comment]
Changing https://github.com/fiatjaf/scoin/blob/master/native/src/main/scala/Crypto.scala#L10 to a `lazy val halfCurveOrder = N.shiftRight(1)` fixed it.
